### ISSUE TITLE
How to use NFCReader?

### ISSUE THREAD

**Issue by MrozuLuL** [MrJPGames/NFCReader#2]

**Comment by dhorlick** [comment]
Based on [main.cpp](https://github.com/MrJPGames/NFCReader/blob/master/source/main.cpp), I think it's supposed to just continuously scan for NFC's once started. Assuming that's correct, it doesn't seem to work on my own New 3DS XL (which can read Amiibos just fine from Amiibo Settings…Register)

Currently, when calling nfcGetTagState() it neither handles NFC_TagState_DataReady message nor checks for error results, so I suspect that luck is an important factor in its successful operation…

**Comment by MrJPGames** [comment]
Luck is not needed. It just supports a very small range of RFID devices and will only look for the UID. It has a 100% success rate with supported devices. If using it with any other RFID tag that does not have this specific 0x4 UID it will not work.
